import type { MenuTemplate, MenuItemData, MenuDesign } from "./types";
import { CANVAS_W, CANVAS_H } from "./types";
import { createText, createMenuList, createShape } from "./defaults";

function half(items: MenuItemData[]): [MenuItemData[], MenuItemData[]] {
  const mid = Math.ceil(items.length / 2);
  return [items.slice(0, mid), items.slice(mid)];
}

export const TEMPLATES: MenuTemplate[] = [
  // ─── MINIMAL ───────────────────────────────────────────
  {
    id: "clean-slate",
    name: "Clean Slate",
    description: "Ultra-minimal white canvas with clean typography",
    category: "minimal",
    defaultStyle: { paper: "#FFFFFF", accent: "#1C1C1E", ink: "#1C1C1E" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#FFFFFF",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createText({ x: 40, y: 50, width: 515, height: 45, content: name || "Restaurant", fontSize: 32, fontFamily: "Inter", fontWeight: "700", textAlign: "center", color: "#1C1C1E", zIndex: 2 }),
        createText({ x: 40, y: 100, width: 515, height: 25, content: tagline || "Your tagline here", fontSize: 13, fontFamily: "Inter", fontWeight: "400", textAlign: "center", color: "#8E8E93", zIndex: 2 }),
        createShape({ x: 250, y: 135, width: 95, height: 2, shape: "rect", fill: "#1C1C1E", stroke: "transparent", borderRadius: 1, zIndex: 2 }),
        createMenuList(items.slice(0, 24), { x: 40, y: 160, width: 515, height: 650, listStyle: "minimal", fontSize: 13, fontFamily: "Inter", color: "#1C1C1E", accentColor: "#1C1C1E", itemSpacing: 10, zIndex: 2 }),
      ],
    }),
  },
  {
    id: "dark-mode",
    name: "Dark Mode",
    description: "Sleek dark background with crisp white type",
    category: "minimal",
    defaultStyle: { paper: "#111111", accent: "#FFFFFF", ink: "#FFFFFF" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#111111",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createText({ x: 40, y: 50, width: 515, height: 45, content: name || "Restaurant", fontSize: 34, fontFamily: "Inter", fontWeight: "800", textAlign: "left", color: "#FFFFFF", zIndex: 2 }),
        createText({ x: 40, y: 100, width: 515, height: 22, content: tagline || "Your tagline here", fontSize: 12, fontFamily: "Inter", fontWeight: "400", color: "#666666", zIndex: 2 }),
        createShape({ x: 40, y: 132, width: 40, height: 3, shape: "rect", fill: "#FF6B2C", stroke: "transparent", borderRadius: 2, zIndex: 2 }),
        createMenuList(items.slice(0, 24), { x: 40, y: 160, width: 515, height: 650, listStyle: "minimal", fontSize: 13, fontFamily: "Inter", color: "#FFFFFF", accentColor: "#FF6B2C", itemSpacing: 11, zIndex: 2 }),
      ],
    }),
  },
  {
    id: "mono",
    name: "Mono",
    description: "Black and white with monospace accents",
    category: "minimal",
    defaultStyle: { paper: "#FAFAFA", accent: "#000000", ink: "#000000" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#FAFAFA",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createText({ x: 40, y: 40, width: 515, height: 35, content: (name || "RESTAURANT").toUpperCase(), fontSize: 24, fontFamily: "DM Sans", fontWeight: "700", textAlign: "left", color: "#000000", letterSpacing: 4, textTransform: "uppercase", zIndex: 2 }),
        createShape({ x: 40, y: 82, width: 515, height: 1, shape: "rect", fill: "#000000", stroke: "transparent", zIndex: 2 }),
        createText({ x: 40, y: 90, width: 515, height: 20, content: tagline || "EST. 2024", fontSize: 10, fontFamily: "DM Sans", fontWeight: "400", color: "#666666", letterSpacing: 3, textTransform: "uppercase", zIndex: 2 }),
        createMenuList(items.slice(0, 24), { x: 40, y: 130, width: 515, height: 680, listStyle: "dotted", fontSize: 13, fontFamily: "DM Sans", color: "#000000", accentColor: "#000000", itemSpacing: 12, zIndex: 2 }),
      ],
    }),
  },

  // ─── CLASSIC ───────────────────────────────────────────
  {
    id: "vintage-bistro",
    name: "Vintage Bistro",
    description: "Warm cream paper with elegant serif typography",
    category: "classic",
    defaultStyle: { paper: "#F4EDDD", accent: "#8B5E3C", ink: "#2D1810" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#F4EDDD",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createShape({ x: 30, y: 30, width: 535, height: 782, shape: "rect", fill: "transparent", stroke: "#8B5E3C", strokeWidth: 2, borderRadius: 4, zIndex: 1 }),
        createText({ x: 40, y: 50, width: 515, height: 50, content: name || "Bistro", fontSize: 36, fontFamily: "Playfair Display", fontWeight: "700", fontStyle: "italic", textAlign: "center", color: "#2D1810", zIndex: 2 }),
        createText({ x: 40, y: 105, width: 515, height: 22, content: tagline || "Fine food since 1952", fontSize: 12, fontFamily: "Cormorant Garamond", fontWeight: "400", textAlign: "center", color: "#8B5E3C", letterSpacing: 2, textTransform: "uppercase", zIndex: 2 }),
        createShape({ x: 240, y: 138, width: 115, height: 1, shape: "rect", fill: "#8B5E3C", stroke: "transparent", zIndex: 2 }),
        createMenuList(items.slice(0, 22), { x: 50, y: 160, width: 495, height: 640, listStyle: "dotted", fontSize: 13, fontFamily: "Cormorant Garamond", color: "#2D1810", accentColor: "#8B5E3C", itemSpacing: 11, zIndex: 2 }),
      ],
    }),
  },
  {
    id: "heritage-gold",
    name: "Heritage Gold",
    description: "Deep dark paper with luxurious gold accents",
    category: "classic",
    defaultStyle: { paper: "#1A1A1A", accent: "#D4AF37", ink: "#F4EDDD" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#1A1A1A",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createShape({ x: 25, y: 25, width: 545, height: 792, shape: "rect", fill: "transparent", stroke: "#D4AF37", strokeWidth: 1, borderRadius: 0, zIndex: 1 }),
        createShape({ x: 30, y: 30, width: 535, height: 782, shape: "rect", fill: "transparent", stroke: "#D4AF37", strokeWidth: 1, borderRadius: 0, zIndex: 1 }),
        createText({ x: 40, y: 55, width: 515, height: 45, content: (name || "Heritage").toUpperCase(), fontSize: 28, fontFamily: "Playfair Display", fontWeight: "700", textAlign: "center", color: "#D4AF37", letterSpacing: 6, zIndex: 2 }),
        createText({ x: 40, y: 105, width: 515, height: 20, content: tagline || "A tradition of excellence", fontSize: 11, fontFamily: "Cormorant Garamond", fontWeight: "400", textAlign: "center", color: "#F4EDDD", letterSpacing: 2, zIndex: 2 }),
        createShape({ x: 220, y: 138, width: 155, height: 1, shape: "rect", fill: "#D4AF37", stroke: "transparent", zIndex: 2 }),
        createMenuList(items.slice(0, 22), { x: 50, y: 165, width: 495, height: 640, listStyle: "minimal", fontSize: 13, fontFamily: "Cormorant Garamond", color: "#F4EDDD", accentColor: "#D4AF37", itemSpacing: 11, zIndex: 2 }),
      ],
    }),
  },

  // ─── BOLD ──────────────────────────────────────────────
  {
    id: "bold-statement",
    name: "Bold Statement",
    description: "High-contrast split layout with strong header",
    category: "bold",
    defaultStyle: { paper: "#FFFFFF", accent: "#FF3B30", ink: "#1C1C1E" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#FFFFFF",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createShape({ x: 0, y: 0, width: CANVAS_W, height: 180, shape: "rect", fill: "#FF3B30", stroke: "transparent", zIndex: 1 }),
        createText({ x: 40, y: 40, width: 515, height: 60, content: (name || "BOLD").toUpperCase(), fontSize: 48, fontFamily: "Bebas Neue", fontWeight: "400", textAlign: "left", color: "#FFFFFF", letterSpacing: 3, zIndex: 3 }),
        createText({ x: 40, y: 105, width: 515, height: 22, content: tagline || "Unapologetically delicious", fontSize: 13, fontFamily: "Poppins", fontWeight: "400", color: "rgba(255,255,255,0.85)", zIndex: 3 }),
        createShape({ x: 40, y: 140, width: 50, height: 3, shape: "rect", fill: "#FFFFFF", stroke: "transparent", borderRadius: 2, zIndex: 3 }),
        createMenuList(items.slice(0, 22), { x: 40, y: 210, width: 515, height: 600, listStyle: "bordered", fontSize: 14, fontFamily: "Poppins", color: "#1C1C1E", accentColor: "#FF3B30", itemSpacing: 14, zIndex: 2 }),
      ],
    }),
  },
  {
    id: "neon-pop",
    name: "Neon Pop",
    description: "Dark backdrop with electric neon highlights",
    category: "bold",
    defaultStyle: { paper: "#0A0A0A", accent: "#00FF87", ink: "#FFFFFF" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#0A0A0A",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createText({ x: 40, y: 50, width: 515, height: 55, content: name || "NEON", fontSize: 44, fontFamily: "Bebas Neue", fontWeight: "400", textAlign: "center", color: "#00FF87", letterSpacing: 5, zIndex: 2 }),
        createText({ x: 40, y: 110, width: 515, height: 20, content: tagline || "Glow different", fontSize: 12, fontFamily: "Poppins", fontWeight: "400", textAlign: "center", color: "#666666", letterSpacing: 3, textTransform: "uppercase", zIndex: 2 }),
        createShape({ x: 200, y: 145, width: 195, height: 1, shape: "rect", fill: "#00FF87", stroke: "transparent", zIndex: 2 }),
        createMenuList(items.slice(0, 24), { x: 40, y: 170, width: 515, height: 640, listStyle: "minimal", fontSize: 13, fontFamily: "Poppins", color: "#FFFFFF", accentColor: "#00FF87", itemSpacing: 11, zIndex: 2 }),
      ],
    }),
  },
  {
    id: "color-block",
    name: "Color Block",
    description: "Playful geometric color blocks with bold type",
    category: "bold",
    defaultStyle: { paper: "#FFCC00", accent: "#FF3B30", ink: "#1C1C1E" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#FFCC00",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createShape({ x: 0, y: 0, width: 200, height: 120, shape: "rect", fill: "#FF3B30", stroke: "transparent", zIndex: 1 }),
        createShape({ x: CANVAS_W - 150, y: CANVAS_H - 100, width: 150, height: 100, shape: "rect", fill: "#007AFF", stroke: "transparent", zIndex: 1 }),
        createText({ x: 40, y: 150, width: 515, height: 55, content: (name || "MENU").toUpperCase(), fontSize: 48, fontFamily: "Montserrat", fontWeight: "800", textAlign: "center", color: "#1C1C1E", zIndex: 2 }),
        createText({ x: 40, y: 210, width: 515, height: 22, content: tagline || "Fun food, bold flavors", fontSize: 13, fontFamily: "Montserrat", fontWeight: "400", textAlign: "center", color: "#1C1C1E", zIndex: 2 }),
        createMenuList(items.slice(0, 20), { x: 50, y: 260, width: 495, height: 540, listStyle: "card", fontSize: 13, fontFamily: "Montserrat", color: "#1C1C1E", accentColor: "#FF3B30", itemSpacing: 10, zIndex: 2 }),
      ],
    }),
  },

  // ─── ELEGANT ───────────────────────────────────────────
  {
    id: "fine-dine",
    name: "Fine Dining",
    description: "Refined spacing and serif elegance for upscale venues",
    category: "elegant",
    defaultStyle: { paper: "#FEFCF8", accent: "#8B5E3C", ink: "#2D1810" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#FEFCF8",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createText({ x: 40, y: 60, width: 515, height: 20, content: "— CARTE —", fontSize: 10, fontFamily: "Cormorant Garamond", fontWeight: "400", textAlign: "center", color: "#8B5E3C", letterSpacing: 6, zIndex: 2 }),
        createText({ x: 40, y: 85, width: 515, height: 50, content: name || "Élégance", fontSize: 38, fontFamily: "Playfair Display", fontWeight: "700", fontStyle: "italic", textAlign: "center", color: "#2D1810", zIndex: 2 }),
        createText({ x: 40, y: 140, width: 515, height: 22, content: tagline || "An exquisite culinary journey", fontSize: 12, fontFamily: "Cormorant Garamond", fontWeight: "400", textAlign: "center", color: "#8B5E3C", letterSpacing: 1, zIndex: 2 }),
        createShape({ x: 260, y: 175, width: 75, height: 1, shape: "rect", fill: "#8B5E3C", stroke: "transparent", zIndex: 2 }),
        createMenuList(items.slice(0, 20), { x: 60, y: 200, width: 475, height: 600, listStyle: "minimal", fontSize: 14, fontFamily: "Cormorant Garamond", color: "#2D1810", accentColor: "#8B5E3C", itemSpacing: 14, showVegDots: false, zIndex: 2 }),
      ],
    }),
  },
  {
    id: "marble",
    name: "Marble",
    description: "Soft gray tones with understated luxury",
    category: "elegant",
    defaultStyle: { paper: "#F0EFED", accent: "#8E8E93", ink: "#3A3A3C" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#F0EFED",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createText({ x: 40, y: 60, width: 515, height: 50, content: name || "Marble", fontSize: 36, fontFamily: "Raleway", fontWeight: "700", textAlign: "center", color: "#3A3A3C", letterSpacing: 3, zIndex: 2 }),
        createShape({ x: 230, y: 118, width: 135, height: 1, shape: "rect", fill: "#8E8E93", stroke: "transparent", zIndex: 2 }),
        createText({ x: 40, y: 130, width: 515, height: 22, content: tagline || "Timeless taste", fontSize: 12, fontFamily: "Raleway", fontWeight: "400", textAlign: "center", color: "#8E8E93", letterSpacing: 2, zIndex: 2 }),
        createMenuList(items.slice(0, 22), { x: 50, y: 175, width: 495, height: 640, listStyle: "bordered", fontSize: 13, fontFamily: "Raleway", color: "#3A3A3C", accentColor: "#8E8E93", itemSpacing: 12, showVegDots: false, zIndex: 2 }),
      ],
    }),
  },

  // ─── CASUAL ────────────────────────────────────────────
  {
    id: "tropical-cafe",
    name: "Tropical Café",
    description: "Bright island vibes with warm sunny accents",
    category: "casual",
    defaultStyle: { paper: "#FFF8ED", accent: "#FF9500", ink: "#2D1810" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#FFF8ED",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createText({ x: 40, y: 40, width: 515, height: 35, content: "🌴", fontSize: 28, fontFamily: "Inter", fontWeight: "400", textAlign: "center", color: "#FF9500", zIndex: 2 }),
        createText({ x: 40, y: 78, width: 515, height: 50, content: name || "Tropical Café", fontSize: 34, fontFamily: "Quicksand", fontWeight: "700", textAlign: "center", color: "#2D1810", zIndex: 2 }),
        createText({ x: 40, y: 130, width: 515, height: 22, content: tagline || "Sunshine on a plate", fontSize: 13, fontFamily: "Quicksand", fontWeight: "400", textAlign: "center", color: "#FF9500", zIndex: 2 }),
        createShape({ x: 220, y: 163, width: 155, height: 2, shape: "rect", fill: "#FF9500", stroke: "transparent", borderRadius: 1, zIndex: 2 }),
        createMenuList(items.slice(0, 22), { x: 40, y: 185, width: 515, height: 630, listStyle: "card", fontSize: 13, fontFamily: "Quicksand", color: "#2D1810", accentColor: "#FF9500", itemSpacing: 10, zIndex: 2 }),
      ],
    }),
  },
  {
    id: "street-food",
    name: "Street Food",
    description: "Energetic layout for casual eateries and food trucks",
    category: "casual",
    defaultStyle: { paper: "#FFFDF5", accent: "#FF6B2C", ink: "#1C1C1E" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#FFFDF5",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createShape({ x: 30, y: 30, width: 535, height: 130, shape: "rect", fill: "#FFFFFF", stroke: "#1C1C1E", strokeWidth: 3, borderRadius: 20, zIndex: 1 }),
        createText({ x: 40, y: 50, width: 515, height: 50, content: name || "Street Eats", fontSize: 38, fontFamily: "Montserrat", fontWeight: "800", textAlign: "center", color: "#FF6B2C", zIndex: 2 }),
        createText({ x: 40, y: 105, width: 515, height: 22, content: tagline || "Hot & fresh, always", fontSize: 12, fontFamily: "Montserrat", fontWeight: "400", textAlign: "center", color: "#1C1C1E", zIndex: 2 }),
        createMenuList(items.slice(0, 22), { x: 40, y: 190, width: 515, height: 620, listStyle: "bordered", fontSize: 14, fontFamily: "Nunito", color: "#1C1C1E", accentColor: "#FF6B2C", itemSpacing: 12, zIndex: 2 }),
      ],
    }),
  },
  {
    id: "brunch-spot",
    name: "Brunch Spot",
    description: "Light and airy with handwritten charm",
    category: "casual",
    defaultStyle: { paper: "#FFFFFF", accent: "#34C759", ink: "#3A3A3C" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#FFFFFF",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createText({ x: 40, y: 50, width: 515, height: 55, content: name || "Brunch Spot", fontSize: 40, fontFamily: "Caveat", fontWeight: "700", textAlign: "center", color: "#34C759", zIndex: 2 }),
        createText({ x: 40, y: 110, width: 515, height: 22, content: tagline || "Lazy mornings, great food", fontSize: 13, fontFamily: "Nunito", fontWeight: "400", textAlign: "center", color: "#8E8E93", zIndex: 2 }),
        createShape({ x: 200, y: 145, width: 195, height: 1, shape: "rect", fill: "#34C759", stroke: "transparent", zIndex: 2 }),
        createMenuList(items.slice(0, 22), { x: 40, y: 170, width: 515, height: 640, listStyle: "minimal", fontSize: 14, fontFamily: "Nunito", color: "#3A3A3C", accentColor: "#34C759", itemSpacing: 12, zIndex: 2 }),
      ],
    }),
  },

  // ─── CUISINE ───────────────────────────────────────────
  {
    id: "sushi-zen",
    name: "Sushi Zen",
    description: "Japanese-inspired minimal aesthetic",
    category: "cuisine",
    defaultStyle: { paper: "#FAFAF7", accent: "#C41E3A", ink: "#1C1C1E" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#FAFAF7",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createShape({ x: 50, y: 45, width: 30, height: 30, shape: "circle", fill: "#C41E3A", stroke: "transparent", zIndex: 2 }),
        createText({ x: 40, y: 90, width: 515, height: 45, content: name || "禅 Zen", fontSize: 30, fontFamily: "Lora", fontWeight: "700", textAlign: "left", color: "#1C1C1E", zIndex: 2 }),
        createText({ x: 40, y: 138, width: 515, height: 22, content: tagline || "Harmony in every bite", fontSize: 12, fontFamily: "Lora", fontWeight: "400", color: "#8E8E93", letterSpacing: 1, zIndex: 2 }),
        createShape({ x: 40, y: 170, width: 60, height: 2, shape: "rect", fill: "#C41E3A", stroke: "transparent", zIndex: 2 }),
        createMenuList(items.slice(0, 22), { x: 40, y: 195, width: 515, height: 620, listStyle: "minimal", fontSize: 13, fontFamily: "Lora", color: "#1C1C1E", accentColor: "#C41E3A", itemSpacing: 12, showVegDots: false, zIndex: 2 }),
      ],
    }),
  },
  {
    id: "trattoria",
    name: "Trattoria",
    description: "Rustic Italian warmth with classic charm",
    category: "cuisine",
    defaultStyle: { paper: "#FDF6EC", accent: "#8B4513", ink: "#3A2A1A" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#FDF6EC",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createText({ x: 40, y: 45, width: 515, height: 22, content: "~ MENU ~", fontSize: 11, fontFamily: "Libre Baskerville", fontWeight: "400", textAlign: "center", color: "#8B4513", letterSpacing: 4, zIndex: 2 }),
        createText({ x: 40, y: 72, width: 515, height: 50, content: name || "Trattoria", fontSize: 38, fontFamily: "Libre Baskerville", fontWeight: "700", fontStyle: "italic", textAlign: "center", color: "#3A2A1A", zIndex: 2 }),
        createText({ x: 40, y: 128, width: 515, height: 22, content: tagline || "Cucina della nonna", fontSize: 13, fontFamily: "Libre Baskerville", fontWeight: "400", fontStyle: "italic", textAlign: "center", color: "#8B4513", zIndex: 2 }),
        createShape({ x: 200, y: 162, width: 195, height: 1, shape: "rect", fill: "#8B4513", stroke: "transparent", zIndex: 2 }),
        createMenuList(items.slice(0, 22), { x: 50, y: 185, width: 495, height: 630, listStyle: "dotted", fontSize: 13, fontFamily: "Libre Baskerville", color: "#3A2A1A", accentColor: "#8B4513", itemSpacing: 12, zIndex: 2 }),
      ],
    }),
  },
  {
    id: "tandoor-spice",
    name: "Tandoor Spice",
    description: "Rich Indian colors with ornate accents",
    category: "cuisine",
    defaultStyle: { paper: "#FFF5E6", accent: "#D4AF37", ink: "#5C1A0A" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#FFF5E6",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createShape({ x: 20, y: 20, width: 555, height: 802, shape: "rect", fill: "transparent", stroke: "#D4AF37", strokeWidth: 2, borderRadius: 8, zIndex: 1 }),
        createText({ x: 40, y: 50, width: 515, height: 55, content: name || "Tandoor & Spice", fontSize: 34, fontFamily: "Playfair Display", fontWeight: "700", textAlign: "center", color: "#5C1A0A", zIndex: 2 }),
        createText({ x: 40, y: 110, width: 515, height: 22, content: tagline || "Authentic flavors from the clay oven", fontSize: 12, fontFamily: "Lora", fontWeight: "400", fontStyle: "italic", textAlign: "center", color: "#D4AF37", zIndex: 2 }),
        createShape({ x: 220, y: 145, width: 155, height: 2, shape: "rect", fill: "#D4AF37", stroke: "transparent", borderRadius: 1, zIndex: 2 }),
        createMenuList(items.slice(0, 22), { x: 40, y: 175, width: 515, height: 630, listStyle: "bordered", fontSize: 13, fontFamily: "Lora", color: "#5C1A0A", accentColor: "#D4AF37", itemSpacing: 11, zIndex: 2 }),
      ],
    }),
  },

  // ─── THEMED ────────────────────────────────────────────
  {
    id: "cafe-chalkboard",
    name: "Chalkboard",
    description: "Dark green blackboard with chalk-white lettering",
    category: "themed",
    defaultStyle: { paper: "#1B2826", accent: "#F4EDDD", ink: "#F4EDDD" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#1B2826",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createShape({ x: 20, y: 20, width: 555, height: 802, shape: "rect", fill: "transparent", stroke: "rgba(244,237,221,0.3)", strokeWidth: 1, borderRadius: 0, zIndex: 1 }),
        createText({ x: 40, y: 50, width: 515, height: 55, content: name || "Café", fontSize: 42, fontFamily: "Caveat", fontWeight: "700", textAlign: "center", color: "#F4EDDD", zIndex: 2 }),
        createText({ x: 40, y: 108, width: 515, height: 22, content: tagline || "Handcrafted with love", fontSize: 13, fontFamily: "Caveat", fontWeight: "400", textAlign: "center", color: "rgba(244,237,221,0.7)", zIndex: 2 }),
        createShape({ x: 200, y: 142, width: 195, height: 1, shape: "rect", fill: "rgba(244,237,221,0.4)", stroke: "transparent", zIndex: 2 }),
        createMenuList(items.slice(0, 22), { x: 40, y: 168, width: 515, height: 640, listStyle: "minimal", fontSize: 14, fontFamily: "Caveat", color: "#F4EDDD", accentColor: "#F4EDDD", itemSpacing: 12, zIndex: 2 }),
      ],
    }),
  },
  {
    id: "retro-diner",
    name: "Retro Diner",
    description: "1950s Americana with cherry red and cream",
    category: "themed",
    defaultStyle: { paper: "#FFF5F0", accent: "#FF2D55", ink: "#1C1C1E" },
    build: (items, name, tagline) => ({
      name: "Untitled",
      canvasWidth: CANVAS_W,
      canvasHeight: CANVAS_H,
      backgroundColor: "#FFF5F0",
      backgroundImage: null,
      backgroundOpacity: 1,
      elements: [
        createShape({ x: 0, y: 0, width: CANVAS_W, height: 10, shape: "rect", fill: "#FF2D55", stroke: "transparent", zIndex: 1 }),
        createShape({ x: 0, y: CANVAS_H - 10, width: CANVAS_W, height: 10, shape: "rect", fill: "#FF2D55", stroke: "transparent", zIndex: 1 }),
        createText({ x: 40, y: 35, width: 515, height: 55, content: (name || "RETRO DINER").toUpperCase(), fontSize: 42, fontFamily: "Bebas Neue", fontWeight: "400", textAlign: "center", color: "#FF2D55", letterSpacing: 4, zIndex: 2 }),
        createText({ x: 40, y: 95, width: 515, height: 22, content: tagline || "Good food, good times ★", fontSize: 12, fontFamily: "Poppins", fontWeight: "400", textAlign: "center", color: "#1C1C1E", zIndex: 2 }),
        createShape({ x: 180, y: 128, width: 235, height: 2, shape: "rect", fill: "#FF2D55", stroke: "transparent", borderRadius: 1, zIndex: 2 }),
        createMenuList(items.slice(0, 22), { x: 40, y: 155, width: 515, height: 660, listStyle: "bordered", fontSize: 14, fontFamily: "Poppins", color: "#1C1C1E", accentColor: "#FF2D55", itemSpacing: 12, zIndex: 2 }),
      ],
    }),
  },
];

export function templateById(id: string): MenuTemplate | undefined {
  return TEMPLATES.find((t) => t.id === id);
}
