import { Platform, type StyleProp, type TextStyle } from "react-native";
import { MaterialIcons } from "@expo/vector-icons";
import { SymbolView } from "expo-symbols";

// SF Symbol name -> Material Icons fallback
const fallback: Record<string, keyof typeof MaterialIcons.glyphMap> = {
  "house.fill": "home",
  "magnifyingglass": "search",
  "calendar": "event",
  "person.fill": "person",
  "cart.fill": "shopping-cart",
  "bell.fill": "notifications",
  "star.fill": "star",
  "location.fill": "location-on",
  "clock.fill": "access-time",
  "chevron.right": "chevron-right",
  "chevron.left": "chevron-left",
  "chevron.down": "expand-more",
  "xmark": "close",
  "plus": "add",
  "minus": "remove",
  "checkmark": "check",
  "checkmark.circle.fill": "check-circle",
  "qrcode.viewfinder": "qr-code-scanner",
  "qrcode": "qr-code",
  "flame.fill": "local-fire-department",
  "leaf.fill": "eco",
  "crown.fill": "workspace-premium",
  "fork.knife": "restaurant",
  "photo.fill": "photo",
  "creditcard.fill": "credit-card",
  "gear": "settings",
  "ellipsis": "more-horiz",
  "arrow.right": "arrow-forward",
  "arrow.left": "arrow-back",
  "arrow.up.right": "north-east",
  "phone.fill": "phone",
  "envelope.fill": "email",
  "map.fill": "map",
  "heart.fill": "favorite",
  "heart": "favorite-border",
  "square.and.arrow.up": "ios-share",
  "tray.fill": "inbox",
  "cup.and.saucer.fill": "coffee",
  "birthday.cake.fill": "cake",
  "fish.fill": "set-meal",
  "sunrise.fill": "wb-sunny",
  "circle.grid.cross.fill": "apps",
  "gift.fill": "redeem",
  "tag.fill": "local-offer",
  "sparkles": "auto-awesome",
  "lock.fill": "lock",
  "trash": "delete",
  "pencil": "edit",
  "info.circle": "info",
  "exclamationmark.triangle.fill": "warning",
  "hand.raised.fill": "pan-tool",
  "flag.fill": "flag",
  "bag.fill": "shopping-bag",
  "shippingbox.fill": "inventory",
  "chart.bar.fill": "bar-chart",
  "chart.line.uptrend.xyaxis": "trending-up",
  "tablecells": "table-chart",
  "doc.text.fill": "description",
  "building.2.fill": "apartment",
  "globe": "language",
  "wifi": "wifi",
  "car.fill": "directions-car",
  "snowflake": "ac-unit",
  "music.note": "music-note",
  "dog.fill": "pets",
  "arrow.uturn.backward": "undo",
  "arrow.uturn.forward": "redo",
  "minus.magnifyingglass": "zoom-out",
  "plus.magnifyingglass": "zoom-in",
  "textformat": "text-fields",
  "list.bullet": "format-list-bulleted",
  "square.fill": "crop-square",
  "circle.fill": "circle",
  "paintbrush.fill": "brush",
  "plus.circle.fill": "add-circle",
  "slider.horizontal.3": "tune",
  "doc.on.doc": "content-copy",
  "doc.fill": "description",
  "arrow.down.circle.fill": "file-download",
  "text.alignleft": "format-align-left",
  "text.aligncenter": "format-align-center",
  "text.alignright": "format-align-right",
  "chevron.up": "expand-less",
  "printer.fill": "print",
  "photo.on.rectangle": "photo-library",
  "arrow.clockwise": "refresh",
  "arrow.counterclockwise": "replay",
  "arrow.triangle.2.circlepath": "sync",
  "person.3.fill": "groups",
  "photo.badge.plus.fill": "add-a-photo",
  "bolt.fill": "bolt",
  "briefcase.fill": "work",
  "moon.fill": "dark-mode",
  "party.popper.fill": "celebration",
  "questionmark.circle": "help",
  "mappin": "place",
  "mappin.and.ellipse": "place",
  "text.bubble.fill": "chat-bubble",
  // Sidebar collapse / expand
  "sidebar.left": "menu-open",
  "sidebar.right": "menu",
  "line.3.horizontal": "menu",
  "chevron.up.chevron.down": "unfold-more",
  // Owner module nav fallbacks
  "xmark.circle": "remove-circle-outline",
  "xmark.circle.fill": "cancel",
  "trash.fill": "delete",
  "scale.3d": "balance",
  "indianrupeesign.circle.fill": "currency-rupee",
  "indianrupeesign.circle": "currency-rupee",
  "currency.rupee": "currency-rupee",
  // Numeric / state icons used in stat tiles
  "checkmark.circle": "check-circle-outline",
  "arrow.up.arrow.down": "swap-vert",
  "hourglass": "hourglass-empty",
  "percent": "percent",
  "play.fill": "play-arrow",
  "stop.fill": "stop",
  "person.2.fill": "people",
  "banknote.fill": "payments",
  "paperplane.fill": "send",
  "send": "send",
  "filter": "filter-alt",
  "chart.line.up.right": "trending-up",
  "wineglass.fill": "wine-bar",
  "figure.walk": "directions-walk",
  "figure.2.and.child.holdinghands": "family-restroom",
  "figure.roll": "accessible",
  "smoke.fill": "smoking-rooms",
  "pawprint.fill": "pets",
  "camera.fill": "photo-camera",
  "location.north.fill": "navigation",
  "arrow.triangle.turn.up.right.diamond.fill": "directions",
  "mappin.circle.fill": "place",
  "f.square.fill": "facebook",
  "bird.fill": "flutter-dash",
  "pin.fill": "push-pin",
  "link": "link",
  "square.grid.2x2.fill": "grid-view",
  "photo": "photo",
  "truck.box.fill": "local-shipping",
  "shippingbox": "inventory",
  "megaphone.fill": "campaign",
  "speaker.wave.2.fill": "campaign",
  "fork.knife.circle": "restaurant-menu",
  "list.clipboard.fill": "list-alt",
  "calendar.badge.checkmark": "event-available",
  "rectangle.split.3x1.fill": "view-week",
  "checkmark.seal.fill": "verified",
  "checkmark.seal": "verified-user",
};

type Props = {
  name: string;
  size?: number;
  color?: string;
  style?: StyleProp<TextStyle>;
};

export function Icon({ name, size = 20, color = "#1C1C1E", style }: Props) {
  if (Platform.OS === "ios") {
    return <SymbolView name={name as never} size={size} tintColor={color} style={style as never} />;
  }
  const mi = fallback[name] ?? "circle";
  return <MaterialIcons name={mi} size={size} color={color} style={style} />;
}
